# Change these first
owner: TheRealDuckers # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  status-website:
  baseUrl: /upptime # where "repo" is your repository name
  name: duckers Dev status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "duckers dev status"
  introMessage: This is the status page for duckers tools.
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/TheRealDuckers

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
